# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Build settings

markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

permalink: /:categories/:title/

sass:
  style: compact

# Site details

title: "Aaron Moodie"
email: "hello@aaronmoodie.com"
description: >- # this means to ignore newlines until "baseurl:"
  Aaron Moodie is a Melbourne based product designer.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://aaronmoodie.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: "aaronmoodie"
github_username: "aaronmoodie"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - bin
  - node_modules
  - .gitignore
  - todo.md
